---
- name: Install Google Chrome
  hosts: 4.194.3.250
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Google Chrome APT repository key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome APT repository
      apt_repository:
        repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present

